### ISSUE TITLE
feature request: remove all the tutorial button

### ISSUE THREAD

**Issue by fafaraway** [ketho-wow/HideTutorial#1]
![_8 HP~JXO1BG6%_HS3IFI8I](https://user-images.githubusercontent.com/156806/204254246-5f4c8cc5-e9cb-4d41-84b7-d1fbcab9fc1b.png)

**Comment by Ketho** [comment]
mmm that sounds a bit overzealous 🙈

**Comment by fafaraway** [comment]
well, just think these buttons are too ugly 😊
